### ISSUE TITLE
Intermittent (but frequent) failure when running `nix flake check -L`

### ISSUE THREAD

**Issue by olirice** [supabase/postgres#1092] opened 2024-08-06 15:01 UTC
# Bug report
```
nix flake check -L
```

Raises the following error about 70% of the time when running reapeatedly

<img width="1088" alt="Screenshot 2024-08-06 at 10 00 29 AM" src="https://github.com/user-attachments/assets/c6129d75-dc4d-4615-9567-b3afc6a0405c">

**Comment by samrose** [comment] 2024-08-20 17:56
I am looking into this, but also breaking out the tests that nix flake check runs into "flake apps" that can just be run outside of the https://nix.dev/manual/nix/2.24/command-ref/new-cli/nix3-flake-check context

We can still use nix flake check in CI, and it can run the same tests optimally

**Comment by samrose** [comment] 2024-10-31 18:52
I think this might have been a configuration issue. If ok, I will close this as I cannot reproduce. We can re-open if you still see intermittent/frequent failure

**Closed as completed by samrose** 2024-10-31 18:52 UTC
Labels: bug
