### ISSUE TITLE
vector extension   did not work correctly

### ISSUE THREAD

**Issue by zhaojunfeng** [supabase/postgres#934] opened 2024-04-04 06:56 UTC
# Bug report

## Describe the bug
vector extension   did not work correctly,  when I exec query :select '[0,0.4345234,0.3434]'<=>'[0,0.234324,0.23123]',  respond with error msg 'Error: Connection terminated unexpectedly'.

select '[0,0.4345234,0.3434]'<=>'[0,0.234324,0.23123]'
2024-04-04T06:22:07.952635613Z 
2024-04-04T06:22:07.952673563Z  2024-04-04 06:22:07.952 UTC [10] LOG:  terminating any other active server processes
2024-04-04T06:22:07.956696604Z  2024-04-04 06:22:07.956 UTC [10] LOG:  all server processes terminated; reinitializing
2024-04-04T06:22:08.120490768Z  2024-04-04 06:22:08.120 UTC [7479] LOG:  database system was interrupted; last known up at 2024-04-04 03:42:01 UTC
2024-04-04T06:22:08.121614013Z 192.168.240.7 2024-04-04 06:22:08.121 UTC [7482] authenticator@postgres FATAL:  the database system is in recovery mode
2024-04-04T06:22:08.122010281Z 192.168.240.7 2024-04-04 06:22:08.121 UTC [7483] authenticator@postgres FATAL:  the database system is in recovery mode
2024-04-04T06:22:08.122262572Z 192.168.240.8 2024-04-04 06:22:08.122 UTC [7484] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
2024-04-04T06:22:08.202609044Z  2024-04-04 06:22:08.202 UTC [7479] LOG:  database system was not properly shut down; automatic recovery in progress

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

exec query 'select '[0,0.4345234,0.3434]'<=>'[0,0.234324,0.23123]' in supabase 'SQL Editor'.
<img width="1388" alt="1712213376385" src="https://github.com/supabase/postgres/assets/8602860/fd4011a4-3d7d-4780-9634-bd75508cb5ea">

## Expected behavior
return correct result 

## System information

- OS: [centos 7.9]
-supabase cli: 1.153.3  (self hosting with docker)

## Additional context
init with pgvector 0.51

![1712213726262](https://github.com/supabase/postgres/assets/8602860/9b672b77-ea90-4fc4-906b-09d295cd207b)

**Comment by olirice** [comment] 2024-08-07 18:11
I was not able to reproduce this on 15.1.1.86

Could you please confirm the issue is still present for you by running
```
docker run -it --name supag -p 5535:5432 -d -e POSTGRES_DB=postgres -e POSTGRES_PASSWORD=local_pw -e POSTGRES_USER=postgres -d supabase/postgres:15.1.1.86
```

to spin up a local instance of supabase in docker and then connecting and executing your repro step
```
select '[0,0.4345234,0.3434]'<=>'[0,0.234324,0.23123]'
```

and let me know how that goes?

**Comment by zhaojunfeng** [comment] 2024-08-08 00:52
In ubantu, it is correct.
In centos 7.9, it happed

**Comment by olirice** [comment] 2024-08-08 17:47
Do you mean that running via docker in centos 7.9 produces the problem, or something else?

**Comment by olirice** [comment] 2024-08-13 14:42
Being tracked upstream
Here https://github.com/pgvector/pgvector/issues/389
and even further upstream https://redmine.postgresql.org/issues/7920

Closing here

**Closed as completed by olirice** 2024-08-13 14:42 UTC
Labels: bug
